import os
import json

def parse_markdown_question(filepath):
    with open(filepath, "r") as f:
        content = f.read()
        
    parts = content.split("---")
    if len(parts) < 3:
        raise ValueError("Invalid markdown format: missing frontmatter")
        
    frontmatter_raw = parts[1].strip()
    body = parts[2].strip()
    
    # Parse frontmatter
    q_data = {}
    for line in frontmatter_raw.split("\n"):
        line = line.strip()
        if ":" in line:
            k, v = line.split(":", 1)
            k = k.strip()
            v = v.strip()
            # Handle numeric values
            if k in ["year", "marks"]:
                q_data[k] = int(v)
            else:
                q_data[k] = v
                
    # Extract sections
    q_idx = body.find("# Question")
    o_idx = body.find("# Options")
    e_idx = body.find("# Explanation")
    
    if q_idx == -1 or o_idx == -1 or e_idx == -1:
        raise ValueError("Missing required headers (# Question, # Options, or # Explanation)")
        
    q_data["question_text"] = body[q_idx + len("# Question") : o_idx].strip()
    
    options_text = body[o_idx + len("# Options") : e_idx].strip()
    options = {}
    for line in options_text.split("\n"):
        line = line.strip()
        if line.startswith("- **") and "**:" in line:
            opt_part = line.split("**:", 1)
            opt_key = opt_part[0].replace("- **", "").replace("**", "").strip()
            opt_val = opt_part[1].strip()
            options[opt_key] = opt_val
    q_data["options"] = options
    
    q_data["explanation"] = body[e_idx + len("# Explanation") :].strip()
    
    return q_data

def compile_database():
    questions_base = "questions"
    all_questions = []
    
    if not os.path.exists(questions_base):
        print("Error: questions folder does not exist. Run generate_questions.py first.")
        return
        
    for root, dirs, files in os.walk(questions_base):
        for file in files:
            if file.endswith(".md"):
                filepath = os.path.join(root, file)
                try:
                    q_data = parse_markdown_question(filepath)
                    all_questions.append(q_data)
                except Exception as e:
                    print(f"Error reading {filepath}: {e}")
                    
    # Sort questions by ID for consistency
    all_questions.sort(key=lambda x: x["id"])
    
    os.makedirs("dashboard/data", exist_ok=True)
    output_path = "dashboard/data/questions_db.js"
    
    with open(output_path, "w") as f:
        f.write("// Auto-generated by compile_db.py from Markdown files - DO NOT EDIT DIRECTLY\n")
        f.write("const QUESTIONS_DATABASE = ")
        json.dump(all_questions, f, indent=2)
        f.write(";\n")
        
    print(f"Compiled {len(all_questions)} questions into {output_path}")

if __name__ == "__main__":
    compile_database()
